[package]
name = "macro_test"
version = "0.1.0"
authors = ["AntiInsect <wangshsh2@shanghaitech.edu.cn>"]
edition = "2018"

[dependencies]
hello_macro = { path = "../hello_macro" }
hello_macro_derive = { path = "../hello_macro/hello_macro_derive" }
